# Numpy->works with raw array(just values,no labels

# pandas -> pandas works with labeled data (value+index+column names)

# by default the labels are given with values in pandas that can be custom change

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

Create a pandas series

In [3]:
s=pd.Series([10,20,30,40,50])

In [4]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s.values

array([10, 20, 30, 40, 50])

Create Series with custom index

In [6]:
z2=pd.Series([10,20,30,40,50],index=['a','b','c','d','e']) #in pandas we can do custom indexing that numpy does not support

In [7]:
z2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [8]:
z2.values

array([10, 20, 30, 40, 50])

Create Series from dictionary

In [9]:
data={'a':10,'b':20,'c':30,'d':40,'e':50}
s2=pd.Series(data)

In [10]:
s2

a    10
b    20
c    30
d    40
e    50
dtype: int64

Make dataframe from dictionary

In [11]:
data= {
    'Math':[80,85,89],
    'Science':[99,90,98],
    'English':[78,87,97],
    'SSC':[76,86,96]
}
df=pd.DataFrame(data)
df

   Math  Science  English  SSC
0    80       99       78   76
1    85       90       87   86
2    89       98       97   96

In [12]:
df.values

array([[80, 99, 78, 76],
       [85, 90, 87, 86],
       [89, 98, 97, 96]])

## series->1D(like a column) , dataframe->(Table)

DataFrame with custom index

In [13]:
df=pd.DataFrame(data,index=['a','b','c'])

In [14]:
df

   Math  Science  English  SSC
a    80       99       78   76
b    85       90       87   86
c    89       98       97   96

DataFrame from Series

In [15]:
s1=pd.Series([101,202,303])
s2=pd.Series([10,20,30])
df3=pd.DataFrame({'Coll1':s1,'Coll2':s2})
df3

   Coll1  Coll2
0    101     10
1    202     20
2    303     30

In [16]:
df3.values

array([[101,  10],
       [202,  20],
       [303,  30]])

In [17]:
df3.shape

(3, 2)

In [18]:
df3.query('Coll1>300')

   Coll1  Coll2
2    303     30

In [19]:
df3.query('Coll1>200 & Coll2<30') #Uses columns for conditions# Checks row by row #Returns rows that satisfy condition

   Coll1  Coll2
1    202     20

In [20]:
df3['Coll1'].value_counts()

Coll1
101    1
202    1
303    1
Name: count, dtype: int64

In [21]:
df1 = pd.DataFrame({
    'ShipmentID': [1001, 1002, 1003, 1004, 1005],
    'Origin': ['NY', 'SF', 'Dallas', 'Chicago', 'Miami'],
    'Destination': ['Boston', 'Seattle', 'Houston', 'Atlanta', 'Denver'],
    'Weight_kg': [12.5, 8.0, 15.0, 7.5, 10.0],
    'Fragile': [True, False, True, False, True],
    'Status': ['Delivered', 'In Transit', 'Delayed', 'Delivered', 'Delayed']
})

In [22]:
df1

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status
0        1001       NY      Boston       12.5     True   Delivered
1        1002       SF     Seattle        8.0    False  In Transit
2        1003   Dallas     Houston       15.0     True     Delayed
3        1004  Chicago     Atlanta        7.5    False   Delivered
4        1005    Miami      Denver       10.0     True     Delayed

In [23]:
df1.shape

(5, 6)

In [24]:
df1.dtypes #multiple strings are considered as object in pandas

ShipmentID       int64
Origin          object
Destination     object
Weight_kg      float64
Fragile           bool
Status          object
dtype: object

In [25]:
df1['ShipmentID'] #the resule is in Series

0    1001
1    1002
2    1003
3    1004
4    1005
Name: ShipmentID, dtype: int64

In [26]:
df1.info() #info in a function

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ShipmentID   5 non-null      int64
 1   Origin       5 non-null      object
 2   Destination  5 non-null      object
 3   Weight_kg    5 non-null      float64
 4   Fragile      5 non-null      bool
 5   Status       5 non-null      object
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 337.0+ bytes

In [27]:
df1['Status']

0     Delivered
1    In Transit
2       Delayed
3     Delivered
4       Delayed
Name: Status, dtype: object

# value_counts is afunction that gives the counts frequency,#.values is a attribute  that converts series|DataFrame to numpy array(removes indexs & columns)

In [28]:
df1['Status'].value_counts()

Status
Delivered     2
Delayed       2
In Transit    1
Name: count, dtype: int64

In [29]:
df1.values

array([[1001, 'NY', 'Boston', 12.5, True, 'Delivered'],
       [1002, 'SF', 'Seattle', 8.0, False, 'In Transit'],
       [1003, 'Dallas', 'Houston', 15.0, True, 'Delayed'],
       [1004, 'Chicago', 'Atlanta', 7.5, False, 'Delivered'],
       [1005, 'Miami', 'Denver', 10.0, True, 'Delayed']], dtype=object)

In [30]:
df1.columns

Index(['ShipmentID', 'Origin', 'Destination', 'Weight_kg', 'Fragile',
       'Status'],
      dtype='object')

In [31]:
data = {
    'A': [101,102,103],
    'B':[201,202,203],
    'C': [301,302,303]
    }
s1 = pd.DataFrame(data, index=['a','b','c'])
s1

     A    B    C
a  101  201  301
b  102  202  302
c  103  203  303

Select column

In [32]:
s1['B'] #to access a column just write name in the column

a    201
b    202
c    203
Name: B, dtype: int64

In [33]:
s1[['A','C']] #to access two columns use 2 []

     A    C
a  101  301
b  102  302
c  103  303

Multiple columns

In [34]:
s1['A']*s1['B']

a    20301
b    20604
c    20909
dtype: int64

loc (label-based)

In [35]:
s1.loc['b']

A    102
B    202
C    302
Name: b, dtype: int64

iloc (index-based)

In [36]:
s1.iloc[1]

A    102
B    202
C    302
Name: b, dtype: int64

In [37]:
print(s1.loc['b','A'])

102

In [38]:
print(s1.loc['c','A'])

103

In [39]:
print(s1.loc['b','C'])

302

How will you filter rows where Weight > 10 using loc?

In [40]:
df1

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status
0        1001       NY      Boston       12.5     True   Delivered
1        1002       SF     Seattle        8.0    False  In Transit
2        1003   Dallas     Houston       15.0     True     Delayed
3        1004  Chicago     Atlanta        7.5    False   Delivered
4        1005    Miami      Denver       10.0     True     Delayed

In [41]:
df1['Weight_kg']

0    12.5
1     8.0
2    15.0
3     7.5
4    10.0
Name: Weight_kg, dtype: float64

In [42]:
df1['Weight_kg']>10

0     True
1    False
2     True
3    False
4    False
Name: Weight_kg, dtype: bool

In [43]:
df1[df1['Weight_kg']>10]

   ShipmentID  Origin Destination  Weight_kg  Fragile     Status
0        1001      NY      Boston       12.5     True  Delivered
2        1003  Dallas     Houston       15.0     True    Delayed

How will you select only 'Destination' column?

In [44]:
df1['Destination']

0     Boston
1    Seattle
2    Houston
3    Atlanta
4     Denver
Name: Destination, dtype: object

Cost = Weight * 10? #adding a new colomn in the exting dataframe

In [45]:
df1['Cost']=df1['Weight_kg']*10

In [46]:
df1

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status   Cost
0        1001       NY      Boston       12.5     True   Delivered  125.0
1        1002       SF     Seattle        8.0    False  In Transit   80.0
2        1003   Dallas     Houston       15.0     True     Delayed  150.0
3        1004  Chicago     Atlanta        7.5    False   Delivered   75.0
4        1005    Miami      Denver       10.0     True     Delayed  100.0

In [47]:
import pandas as pd

df7 = pd.DataFrame({
    'Name': ['Amit', 'Sara', 'John', 'Priya', 'Ravi'],
    'Math': [80, 90, 75, 85, 60],
    'Science': [70, 95, 80, 75, 65],
    'Passed': [True, True, True, True, False]
})

In [48]:
df7

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True
4   Ravi    60       65   False

How many rows and columns are there?

In [49]:
df7.shape

(5, 4)

What are the column names?

In [50]:
df7.columns

Index(['Name', 'Math', 'Science', 'Passed'], dtype='object')

What is the data type of each column?

In [51]:
df7.dtypes

Name       object
Math        int64
Science     int64
Passed       bool
dtype: object

How will you select only the Math marks column?

In [52]:
df7['Math']

0    80
1    90
2    75
3    85
4    60
Name: Math, dtype: int64

How will you select Name and Science columns together?

In [53]:
df7[['Name','Science']]

    Name  Science
0   Amit       70
1   Sara       95
2   John       80
3  Priya       75
4   Ravi       65

How will you get the first row?

In [54]:
df7.loc[0]

Name       Amit
Math         80
Science      70
Passed     True
Name: 0, dtype: object

How will you get the last row?

In [55]:
df7.loc[4]

Name        Ravi
Math          60
Science       65
Passed     False
Name: 4, dtype: object

In [56]:
df7

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True
4   Ravi    60       65   False

How will you get the 2nd row and 3rd column value?

In [57]:
print(df7.loc[1,'Science'])

95

In [58]:
print(df7.iloc[1,2])

95

How will you get first 3 rows?

In [59]:
df7[0:3]

   Name  Math  Science  Passed
0  Amit    80       70    True
1  Sara    90       95    True
2  John    75       80    True

How will you get rows 2 to 4 and columns 1 to 2?

In [60]:
df7

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True
4   Ravi    60       65   False

In [61]:
df7.iloc[1:4,0:2]

    Name  Math
1   Sara    90
2   John    75
3  Priya    85

In [62]:
df7.iloc[2:,1:]

   Math  Science  Passed
2    75       80    True
3    85       75    True
4    60       65   False

In [63]:
df7.iloc[0:2,0:]

   Name  Math  Science  Passed
0  Amit    80       70    True
1  Sara    90       95    True

How will you get all students who passed?

In [64]:
df7['Passed']==True

0     True
1     True
2     True
3     True
4    False
Name: Passed, dtype: bool

In [65]:
df7[df7['Passed']==True]

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True

How will you get students with Math > 80 AND Science > 80?

In [66]:
(df7['Math']>80)&(df7['Science']>80)

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [67]:
df7[(df7['Math']>80)&(df7['Science']>80)]

   Name  Math  Science  Passed
1  Sara    90       95    True

How will you create a new column Total = Math + Science?

In [68]:
df7['Total']=df7['Math']+df7['Science']

In [69]:
df7

    Name  Math  Science  Passed  Total
0   Amit    80       70    True    150
1   Sara    90       95    True    185
2   John    75       80    True    155
3  Priya    85       75    True    160
4   Ravi    60       65   False    125

How will you create Average marks?

In [70]:
df7['Average']=df7['Total']/2

In [71]:
df7

    Name  Math  Science  Passed  Total  Average
0   Amit    80       70    True    150     75.0
1   Sara    90       95    True    185     92.5
2   John    75       80    True    155     77.5
3  Priya    85       75    True    160     80.0
4   Ravi    60       65   False    125     62.5

Above 80 → Excellent, else Average. Create new column called category

In [72]:
def grade(marks):
    if marks>=80:
        return "Excellent"
    elif marks>=50:
        return "Average"

In [73]:
df7['Category']=df7['Average'].apply(grade)

In [74]:
df7

    Name  Math  Science  Passed  Total  Average   Category
0   Amit    80       70    True    150     75.0    Average
1   Sara    90       95    True    185     92.5  Excellent
2   John    75       80    True    155     77.5    Average
3  Priya    85       75    True    160     80.0  Excellent
4   Ravi    60       65   False    125     62.5    Average

How will you label Passed column:

True → "Yes", False → "No"

In [75]:
def sort(X):
    if X==True:
        return "Yes"
    elif X==False:
        return "No"

In [76]:
df7['Label']=df7['Passed'].apply(sort)

In [77]:
df7

    Name  Math  Science  Passed  Total  Average   Category Label
0   Amit    80       70    True    150     75.0    Average   Yes
1   Sara    90       95    True    185     92.5  Excellent   Yes
2   John    75       80    True    155     77.5    Average   Yes
3  Priya    85       75    True    160     80.0  Excellent   Yes
4   Ravi    60       65   False    125     62.5    Average    No

How will you rename column Math → Maths?

In [78]:
df7.rename(columns={'Math':'Maths'},
           inplace=True)                  #inplace=True, it creates a copy & doesn't update df7

In [79]:
df7 #we use dictionary because  a dictionary map old names -> new names

    Name  Maths  Science  Passed  Total  Average   Category Label
0   Amit     80       70    True    150     75.0    Average   Yes
1   Sara     90       95    True    185     92.5  Excellent   Yes
2   John     75       80    True    155     77.5    Average   Yes
3  Priya     85       75    True    160     80.0  Excellent   Yes
4   Ravi     60       65   False    125     62.5    Average    No

How will you drop column Science?

In [ ]:
df7.drop("Science",axis=1)

What is the average Math score of class?

In [80]:
print(df7['Maths'].mean())

78.0

#   many students passed?

In [81]:
df7[df7['Passed']==True].shape[0]
    #filtering show all passed students , .shape show how big the list is , [0] tells just tell how many students

4

In [82]:
print(df7['Passed'].sum()) #works directly  on the coulmns (True 1/false 0)

4

In [83]:
len(df7[df7['Passed']==True]) #len()->counts rows directly

4

In [84]:
df7

    Name  Maths  Science  Passed  Total  Average   Category Label
0   Amit     80       70    True    150     75.0    Average   Yes
1   Sara     90       95    True    185     92.5  Excellent   Yes
2   John     75       80    True    155     77.5    Average   Yes
3  Priya     85       75    True    160     80.0  Excellent   Yes
4   Ravi     60       65   False    125     62.5    Average    No